In [2]:
import torch
from torchmetrics.classification import MulticlassAUROC

In [3]:
a = torch.rand(size=(1,7))
b = torch.rand(size=(1, 7))
c = torch.cat([a, b])
c.shape

torch.Size([2, 7])

In [4]:
d = torch.nn.Softmax(dim=1)(c)
d

tensor([[0.0954, 0.1366, 0.1626, 0.1452, 0.1224, 0.2220, 0.1158],
        [0.2153, 0.1992, 0.1042, 0.1750, 0.0857, 0.1362, 0.0844]])

In [7]:
target = torch.tensor([[0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0]])
targe2 = torch.tensor([[0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0]])
t = target.argmax(dim=1)
t2 = targe2.argmax(dim=1)
tt = torch.cat([p.argmax(dim=1)  for p in [target, targe2]])
# t = torch.tensor([2, 0])
tt

tensor([2, 3, 2, 3])

In [6]:
metric = MulticlassAUROC(num_classes=7, average=None, thresholds=None)
metric(d, t)

/data/Users/xyq/miniconda3/envs/data_mining/lib/python3.11/site-packages/torchmetrics/utilities/prints.py:43: UserWarning: No positive samples in targets, true positive value should be meaningless. Returning zero tensor in true positive score
  warnings.warn(*args, **kwargs)  # noqa: B028


tensor([0., 0., 1., 1., 0., 0., 0.])